version: '3.9'

services:

  database:
    image: mysql:8.1
    container_name: mysql-container
    networks:
      - compose-bridge
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jornadamilhas
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

  api:
    image: jornada-milhas-api
    container_name: api-container
    networks:
      - compose-bridge
    ports:
      - "8080:8080"
    environment:
      DB_HOST: database
      DB_PORT: 3306
    depends_on:
      database:
        condition: service_healthy

networks:
  compose-bridge:
    driver: bridge

# docker compose -p <nome-stack> up