spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:${MYSQL_URL}?createDatabaseIfNotExist=true
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

jwt:
  secret: ${JWT_SECRET}