spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/jornadamilhas?createDatabaseIfNotExist=true
    username: root
    password: root

  data:
    web:
      pageable:
        page-parameter: page

  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: none

logging:
  level:
    org:
      springframework:
        :web: DEBUG

jwt:
  secret: 123456

gpt:
  secret: ${OPENAI_API_KEY:123456}